version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
    networks:
      - todo
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

networks:
  todo:
    external: true

volumes:
  pgdata:
